all:
	@echo Done

update:
	@wget http://sbmaxx.github.com/history.js/scripts/bundled/bem/i-jquery__history.js -O ./i-jquery__history.js
	@wget http://sbmaxx.github.com/history.js/scripts/bundled/bem/i-jquery__history_html4_yes.js -O ./_html4/i-jquery__history_html4_yes.js
