all:
	@echo Done

update:
	@wget http://sbmaxx.github.com/history.js/scripts/bundled/bem/jquery__history.js -O ./jquery__history.js
	@wget http://sbmaxx.github.com/history.js/scripts/bundled/bem/jquery__history_html4_yes.js -O ./_html4/jquery__history_html4_yes.js
